/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Akshat (https://sketchfab.com/shooter24994)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/makeup-kit-cfcf5114727b4eca87a837561e4bc751
Title: Makeup Kit
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/makeup_kit.glb')
  return (
    <group {...props} dispose={null}>
      <group
        position={[94.197, 10.394, -64.008]}
        rotation={[Math.PI / 2, 0, 0.9]}
        scale={[11.117, 12.215, 9.689]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cap001_golden_0.geometry}
          material={materials.golden}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cap001_base_0.geometry}
          material={materials.base}
        />
      </group>
      <group position={[81.314, 11.87, -82.191]} rotation={[-Math.PI / 2, 0, -0.9]} scale={14.477}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.lipstick_crimson_0.geometry}
          material={materials.crimson}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.lipstick_golden_0.geometry}
          material={materials.golden}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.lipstick_base_0.geometry}
          material={materials.base}
        />
      </group>
      <group position={[0, 50.793, -117.04]} rotation={[-0.392, 0, 0]} scale={46.924}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mirror_black_compact_0.geometry}
          material={materials.black_compact}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mirror_silver_0.geometry}
          material={materials.silver}
        />
      </group>
      <group
        position={[76.948, 2.935, -3.506]}
        rotation={[-Math.PI, 1.015, Math.PI / 2]}
        scale={[3.703, 3.703, 60.613]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pencil_penncilColor_0.geometry}
          material={materials.penncilColor}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pencil_pencilW_0.geometry}
          material={materials.pencilW}
        />
      </group>
      <group
        position={[109.074, 5.558, 52.635]}
        rotation={[-Math.PI / 2, 0, -1.272]}
        scale={19.385}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle_golden_0.geometry}
          material={materials.golden}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle_creamBlck_0.geometry}
          material={materials.creamBlck}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle_creamPink_0.geometry}
          material={materials.creamPink}
        />
      </group>
      <group position={[-104.224, 17.333, 26.908]} rotation={[-Math.PI / 2, 0, 0]} scale={18.806}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.bottle_creamBottle_0.geometry}
          material={materials.creamBottle}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.bottle_bottleBlack_0.geometry}
          material={materials.bottleBlack}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane_box_0.geometry}
        material={materials.material}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={137.655}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.base_black_compact_0.geometry}
        material={materials.black_compact}
        position={[0, -0.177, -48.195]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={46.924}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube_Material_0.geometry}
        material={materials.Material}
        position={[0, 12.005, -92.169]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.463, 2.806, 2.806]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.makeup_makeup_0.geometry}
        material={materials.makeup}
        position={[0, 9.952, -48.195]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={38.238}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.makeup001_silver_0.geometry}
        material={materials.silver}
        position={[0, 55.808, -106.196]}
        rotation={[2.75, 0, 0]}
        scale={38.966}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bottle001_nailColor_0.geometry}
        material={materials.nailColor}
        position={[-83.011, 19.284, 99.881]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={20.134}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cap_nailCap_0.geometry}
        material={materials.nailCap}
        position={[-83.022, 54.185, 99.881]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={13.451}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001_cpmb_0.geometry}
        material={materials.cpmb}
        position={[-14.935, -0.723, 57.907]}
        rotation={[Math.PI / 2, 0, 0.262]}
        scale={[41.523, 13.631, 100]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder_spunch001_0.geometry}
        material={materials['spunch.001']}
        position={[-53.645, 28.279, -6.342]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={17.89}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001_spunch001_0.geometry}
        material={materials['spunch.001']}
        position={[-66.5, 28.279, -49.459]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={17.89}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder002_maskaBlck_0.geometry}
        material={materials.maskaBlck}
        position={[-94.519, 9.914, -93.31]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={10.295}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane002_cpmb_0.geometry}
        material={materials.cpmb}
        position={[-90.003, 91.3, -93.031]}
        rotation={[0, 0, Math.PI / 2]}
        scale={[8.464, 2.779, 20.384]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane003_cpmb_0.geometry}
        material={materials.cpmb}
        position={[-98.484, 90.316, -93.031]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[8.464, 2.779, 20.384]}
      />
    </group>
  )
}

useGLTF.preload('/models/makeup_kit.glb')

